INSERT INTO api.cards (name, slug)
VALUES
  ('violence', 'violence'),
  ('caue diabo', 'caue-diabo'),
  ('lucas fast', 'lucas-fast'),
  ('lucas 2m', 'lucas-2m'),
  ('desir', 'desir'),
  ('msx', 'msx'),
  ('deusmelevadesselugar', 'deusmelevadesselugar'),
  ('richard lele', 'richard-lele'),
  ('guizao', 'guizao'),
  ('povoas', 'povoas'),
  ('nev', 'nev'),
  ('dantas', 'dantas'),
  ('zond', 'zond'),
  ('sombra', 'sombra'),
  ('gal', 'gal'),
  ('pizza', 'pizza'),
  ('king ryan', 'king-ryan'),
  ('neythz', 'neythz'),
  ('james', 'james'),
  ('massaru', 'massaru'),
  ('aquilino', 'aquilino'),
  ('dzn', 'dzn'),
  ('ailux', 'ailux'),
  ('suff', 'suff'),
  ('vigarism', 'vigarism'),
  ('fw', 'fw'),
  ('peterw', 'peterw'),
  ('joao desired', 'joao-desired'),
  ('konnorseth', 'konnorseth'),
  ('molinho', 'molinho'),
  ('palavras', 'palavras'),
  ('lucas ben10', 'lucas-ben10'),
  ('joao autista', 'joao-autista'),
  ('taki', 'taki'),
  ('jorel', 'jorel'),
  ('lucas senz', 'lucas-senz'),
  ('lucas nfa', 'lucas-nfa'),
  ('lucas pqex', 'lucas-pqex'),
  ('kis unknown', 'kis-unknown'),
  ('frota', 'frota'),
  ('victim', 'victim'),
  ('gelo', 'gelo'),
  ('pz', 'pz'),
  ('pacheco', 'pacheco'),
  ('pietro', 'pietro'),
  ('casas folda', 'casas-folda'),
  ('artemas', 'artemas'),
  ('nicollas', 'nicollas'),
  ('mikael', 'mikael'),
  ('syxblades', 'syxblades'),
  ('mody', 'mody'),
  ('celibato', 'celibato'),
  ('shano', 'shano'),
  ('kat', 'kat'),
  ('keepo', 'keepo'),
  ('xis', 'xis'),
  ('bernardo motoboy', 'bernardo-motoboy'),
  ('scy', 'scy')
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name;