INSERT INTO api.cards (name, slug)
VALUES
  ('bluster', 'bluster'),
  ('nicolas fiuzen', 'nicolas-fiuzen'),
  ('alaska', 'alaska'),
  ('sabatke', 'sabatke'),
  ('denilson', 'denilson'),
  ('ax', 'ax'),
  ('lis cabelo rosa', 'lis-cabelo-rosa'),
  ('isa based', 'isa-based'),
  ('durock', 'durock'),
  ('isaac', 'isaac'),
  ('marifdse', 'marifdse'),
  ('lucas painkiller', 'lucas-painkiller'),
  ('max', 'max'),
  ('righi', 'righi'),
  ('julia naruto', 'julia-naruto'),
  ('rafael pye', 'rafael-pye'),
  ('nim', 'nim'),
  ('ban', 'ban'),
  ('andre', 'andre'),
  ('yanka balofinhos', 'yanka-balofinhos'),
  ('jess', 'jess'),
  ('bobato', 'bobato'),
  ('victorlol', 'victorlol'),
  ('wang', 'wang'),
  ('chris', 'chris'),
  ('ethan', 'ethan'),
  ('vitor gal', 'vitor-gal'),
  ('artur', 'artur'),
  ('mene', 'mene'),
  ('carolvsts', 'carolvsts'),
  ('magossi', 'magossi'),
  ('balofinhos', 'balofinhos'),
  ('vensay mijao', 'vensay-mijao'),
  ('tormento', 'tormento'),
  ('vinocas', 'vinocas'),
  ('petterw', 'petterw'),
  ('boo', 'boo'),
  ('yasmin behaviorsoul', 'yasmin-behaviorsoul'),
  ('lucas senzs', 'lucas-senzs'),
  ('herick', 'herick'),
  ('charan', 'charan'),
  ('vexy', 'vexy'),
  ('thigas', 'thigas'),
  ('cadeira', 'cadeira'),
  ('igor xines', 'igor-xines'),
  ('exselor', 'exselor'),
  ('link', 'link'),
  ('weed explanada', 'weed-explanada'),
  ('emily ex do alaska', 'emily-ex-do-alaska'),
  ('mauricio homemdoano', 'mauricio-homemdoano'),
  ('maria 38wkn puta rodada', 'maria-38wkn-puta-rodada'),
  ('julie peitos', 'julie-peitos'),
  ('ekivya', 'ekivya'),
  ('violence pedofilo', 'violence-pedofilo'),
  ('wester', 'wester'),
  ('script', 'script'),
  ('laura', 'laura'),
  ('sielle', 'sielle'),
  ('vitinhomtfe', 'vitinhomtfe'),
  ('joao 2ucat', 'joao-2ucat'),
  ('fael', 'fael'),
  ('sloth', 'sloth'),
  ('nicolas chess', 'nicolas-chess'),
  ('cytmagicalmaypole', 'cytmagicalmaypole'),
  ('lucille', 'lucille'),
  ('alangm', 'alangm'),
  ('reduzir', 'reduzir'),
  ('nicolas noites', 'nicolas-noites'),
  ('komicaize', 'komicaize'),
  ('kis nequinho feio', 'kis-nequinho-feio'),
  ('clark', 'clark'),
  ('beelzebulb', 'beelzebulb'),
  ('coopex', 'coopex'),
  ('overslow', 'overslow'),
  ('julia aspen', 'julia-aspen'),
  ('gatosopa', 'gatosopa'),
  ('rebecca bertelli', 'rebecca-bertelli'),
  ('darft', 'darft'),
  ('jhony', 'jhony'),
  ('jk', 'jk'),
  ('kaue bandeira', 'kaue-bandeira'),
  ('pietro kpop', 'pietro-kpop'),
  ('julia dentuça insidedoll', 'julia-dentuca-insidedoll'),
  ('lucas desired', 'lucas-desired'),
  ('bianca preta explanada', 'bianca-preta-explanada'),
  ('matheus yupoi', 'matheus-yupoi'),
  ('zuppa', 'zuppa'),
  ('carunc', 'carunc'),
  ('sentinela', 'sentinela'),
  ('pavement', 'pavement'),
  ('brux', 'brux'),
  ('hypo', 'hypo'),
  ('ledsen', 'ledsen'),
  ('liz lambida por cachorro', 'liz-lambida-por-cachorro'),
  ('kurtz', 'kurtz'),
  ('blasfier', 'blasfier'),
  ('daniel funaci', 'daniel-funaci'),
  ('vidabode', 'vidabode'),
  ('flopinha', 'flopinha'),
  ('bernxrdx', 'bernxrdx'),
  ('manu porcos', 'manu-porcos'),
  ('melissa do sul', 'melissa-do-sul'),
  ('amanha', 'amanha'),
  ('ponei', 'ponei'),
  ('felipe nero pedofilo', 'felipe-nero-pedofilo')
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name;